CREATE TABLE public.mesures (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    capteur_id TEXT NOT NULL,
    capteur_nom TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,

    time TIMESTAMP,

    european_aqi DOUBLE PRECISION,
    pm10 DOUBLE PRECISION,
    pm2_5 DOUBLE PRECISION,
    nitrogen_dioxide DOUBLE PRECISION,
    ozone DOUBLE PRECISION,
    sulphur_dioxide DOUBLE PRECISION,
    carbon_monoxide DOUBLE PRECISION,
    birch_pollen DOUBLE PRECISION,

    temperature_2m DOUBLE PRECISION,
    relative_humidity_2m DOUBLE PRECISION,
    wind_speed_10m DOUBLE PRECISION,
    wind_direction_10m DOUBLE PRECISION,
    precipitation DOUBLE PRECISION
);







--- pour effacer activer l'effacement dans python
CREATE OR REPLACE FUNCTION vider_mesures()
RETURNS void
LANGUAGE sql
SECURITY DEFINER
AS $$
    TRUNCATE TABLE public.mesures;
$$;